CREATE TABLE IF NOT EXISTS ENDERECO (
    CD_CEP           VARCHAR(10) NOT NULL,
    DS_LOGRADOURO    VARCHAR(151),
    DS_COMPLEMENTO   VARCHAR(150),
    NM_BAIRRO        VARCHAR(150),
    NM_LOCALIDADE    VARCHAR(150),
    DS_UF            VARCHAR(2),
    DS_IBGE          VARCHAR(30),
    DS_GIA           VARCHAR(30),
    DS_DDD           VARCHAR(3),
    DS_SIAFI         VARCHAR(30),
    DT_RECORD        DATE,
    CONSTRAINT XPKENDERECO UNIQUE (CD_CEP)
);